const ISRAEL_PARTIES = {
    אמת: {
        id: "אמת",
        hebrewName: "העבודה",
        englishName: "Labor",
    },
    ב: {
        id: "ב",
        hebrewName: "ימינה",
        englishName: "Yamina",
    },
    ג: {
        id: "ג",
        hebrewName: "יהדות התורה",
        englishName: "United Torah Judaism",
    },
    ום: {
        id: "ום",
        hebrewName: "חד״ש־תע״ל",
        englishName: "Hadash-Ta'al",
    },
    ט: {
        id: "ט",
        hebrewName: "הציונות הדתית",
        englishName: "Religious Zionism",
    },
    כן: {
        id: "כן",
        hebrewName: "המחנה הממלכתי",
        englishName: "National Unity",
    },
    ל: {
        id: "ל",
        hebrewName: "ישראל ביתנו",
        englishName: "Yisrael Beiteinu",
    },
    מחל: {
        id: "מחל",
        hebrewName: "הליכוד",
        englishName: "Likud",
    },
    מרצ: {
        id: "מרצ",
        hebrewName: "מרצ",
        englishName: "Meretz",
    },
    עם: {
        id: "עם",
        hebrewName: "רעיימ",
        englishName: "Ra'am",
    },
    פה: {
        id: "פה",
        hebrewName: "יש עתיד",
        englishName: "Yesh Atid",
    },
    שס: {
        id: "שס",
        hebrewName: "שס",
        englishName: "Shas",
    },
    // אצ: 172,
    // ד: 15,
    // ז: 2,
    // זך: 2,
    // זנ: 1,
    // זץ: 3,
    // י: 13,
    // יז: 127,
    // ינ: 1,
    // יץ: 2,
    // יק: 0,
    // ך: 1,
    // נז: 2,
    // ני: 21,
    // נף: 0,
    // נץ: 7,
    // נק: 11,
    // נר: 4,
    // ף: 8,
    // צ: 74,
    // ץ: 3,
    // ק: 10,
    // קי: 0,
    // קך: 14,
    // קנ: 12,
    // קץ: 190,
    // רז: 0,
    // ת: 9,
};
